# Generated by Django 2.2.7 on 2020-04-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbasic', '0002_auto_20200407_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='mobile_name',
            field=models.IntegerField(),
        ),
    ]
