# Generated by Django 2.2.7 on 2020-04-07 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restbasic', '0003_auto_20200407_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
